-Explore and clean data

In [1]:
import pandas as pd

df_test = pd.read_csv('test.csv')
df_train = pd.read_csv('train.csv')


In [2]:
df_train.sort_values('customer_id', inplace=True)
df_train

customer_id  age     income signup_channel  country  account_duration  \
0     CUST100000   56   41315.55            web  Germany                 4   
1     CUST100001   69   50955.33       Referral  Germany                30   
2     CUST100002   46   57079.42            web       UK                30   
3     CUST100003   32   52088.23           APP    Canada                13   
4     CUST100004   60  340461.50            Web    India                42   
...          ...  ...        ...            ...      ...               ...   
2693  CUST102693   27   58571.13            Web       US                59   
2694  CUST102694   20   61771.72            app    India                13   
2695  CUST102695   71   59322.83            Web  Germany                52   
2696  CUST102696   31   45010.14            app  Germany                48   
2697  CUST102697   33   66405.46           APP        UK                42   

      last_login_days  num_transactions  support_tickets premium_user  \
0                55.0                11                2            N   
1               228.0                 9                1          NO    
2               144.0                 9                0           no   
3                91.0                 5                3          NO    
4                81.0                 3                2          Yes   
...               ...               ...              ...          ...   
2693            329.0                 8                2           No   
2694            339.0                 8                2          Yes   
2695              NaN                 9                1          yes   
2696            154.0                10                0         YES    
2697            159.0                 8                2            N   

      satisfaction_score  target  
0                    3.0       1  
1                    NaN       0  
2                    3.0       0  
3                    2.0       0  
4                    2.0       0  
...                  ...     ...  
2693                 5.0       0  
2694                 3.0       0  
2695                 NaN       0  
2696                 2.0       1  
2697                 4.0       0  

[2698 rows x 12 columns]

In [3]:
df_test.sort_values('customer_id', inplace=True)
df_test

customer_id  age    income signup_channel  country  account_duration  \
0    CUST102698   27  48133.59           APP        US                27   
1    CUST102699   46  41464.59       Referral   Canada                53   
2    CUST102700   27  41684.93            app    India                 2   
3    CUST102701   29  79099.83            web       US                34   
4    CUST102702   47  38870.25           APP        US                31   
..          ...  ...       ...            ...      ...               ...   
297  CUST102995   37  26426.33           APP     India                 1   
298  CUST102996   21  38093.20            web   Canada                19   
299  CUST102997   71  52240.34       Referral  Germany                46   
300  CUST102998   24  46921.57            app  Germany                 3   
301  CUST102999   71  32402.65       referral       US                 2   

     last_login_days  num_transactions  support_tickets premium_user  \
0                NaN                 7                1            Y   
1                NaN                10                0            N   
2              167.0                16                2           No   
3              144.0                13                3            Y   
4              185.0                14                0         YES    
..               ...               ...              ...          ...   
297              NaN                 9                3          NO    
298            277.0                15                1            Y   
299             55.0                 9                0         YES    
300            273.0                14                0           No   
301            175.0                17                2          NO    

     satisfaction_score  
0                   5.0  
1                   1.0  
2                   1.0  
3                   3.0  
4                   5.0  
..                  ...  
297                 1.0  
298                 1.0  
299                 2.0  
300                 3.0  
301                 4.0  

[302 rows x 11 columns]

In [4]:
df_test_sub = df_test.drop(columns=['customer_id','signup_channel','country',])
df_test_sub['premium_user'] = df_test_sub['premium_user'].replace({'Y': 1, 'YES': 1, 'Yes': 1, 'yes': 1, 'y': 1, 'N': 0, 'NO': 0, 'No': 0, 'no': 0, 'n': 0,' YES ':1, ' NO ':0})
df_test_sub['premium_user'] = df_test_sub['premium_user'].astype(int)
df_test_sub

C:\Users\emili\AppData\Local\Temp\ipykernel_27908\599400350.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_test_sub['premium_user'] = df_test_sub['premium_user'].replace({'Y': 1, 'YES': 1, 'Yes': 1, 'yes': 1, 'y': 1, 'N': 0, 'NO': 0, 'No': 0, 'no': 0, 'n': 0,' YES ':1, ' NO ':0})


age    income  account_duration  last_login_days  num_transactions  \
0     27  48133.59                27              NaN                 7   
1     46  41464.59                53              NaN                10   
2     27  41684.93                 2            167.0                16   
3     29  79099.83                34            144.0                13   
4     47  38870.25                31            185.0                14   
..   ...       ...               ...              ...               ...   
297   37  26426.33                 1              NaN                 9   
298   21  38093.20                19            277.0                15   
299   71  52240.34                46             55.0                 9   
300   24  46921.57                 3            273.0                14   
301   71  32402.65                 2            175.0                17   

     support_tickets  premium_user  satisfaction_score  
0                  1             1                 5.0  
1                  0             0                 1.0  
2                  2             0                 1.0  
3                  3             1                 3.0  
4                  0             1                 5.0  
..               ...           ...                 ...  
297                3             0                 1.0  
298                1             1                 1.0  
299                0             1                 2.0  
300                0             0                 3.0  
301                2             0                 4.0  

[302 rows x 8 columns]

In [5]:
df_test_sub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   age                 302 non-null    int64  
 1   income              302 non-null    float64
 2   account_duration    302 non-null    int64  
 3   last_login_days     268 non-null    float64
 4   num_transactions    302 non-null    int64  
 5   support_tickets     302 non-null    int64  
 6   premium_user        302 non-null    int64  
 7   satisfaction_score  268 non-null    float64
dtypes: float64(3), int64(5)
memory usage: 19.0 KB


In [6]:
df_train_sub = df_train.drop(columns=['customer_id','signup_channel','country',])
df_train_sub['premium_user'] = df_train_sub['premium_user'].replace({'Y': 1, 'YES': 1, 'Yes': 1, 'yes': 1, 'y': 1, 'N': 0, 'NO': 0, 'No': 0, 'no': 0, 'n': 0,' YES ':1, ' NO ':0})
df_train_sub['premium_user'] = df_train_sub['premium_user'].astype(int)
df_train_sub

C:\Users\emili\AppData\Local\Temp\ipykernel_27908\1379130154.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_train_sub['premium_user'] = df_train_sub['premium_user'].replace({'Y': 1, 'YES': 1, 'Yes': 1, 'yes': 1, 'y': 1, 'N': 0, 'NO': 0, 'No': 0, 'no': 0, 'n': 0,' YES ':1, ' NO ':0})


age     income  account_duration  last_login_days  num_transactions  \
0      56   41315.55                 4             55.0                11   
1      69   50955.33                30            228.0                 9   
2      46   57079.42                30            144.0                 9   
3      32   52088.23                13             91.0                 5   
4      60  340461.50                42             81.0                 3   
...   ...        ...               ...              ...               ...   
2693   27   58571.13                59            329.0                 8   
2694   20   61771.72                13            339.0                 8   
2695   71   59322.83                52              NaN                 9   
2696   31   45010.14                48            154.0                10   
2697   33   66405.46                42            159.0                 8   

      support_tickets  premium_user  satisfaction_score  target  
0                   2             0                 3.0       1  
1                   1             0                 NaN       0  
2                   0             0                 3.0       0  
3                   3             0                 2.0       0  
4                   2             1                 2.0       0  
...               ...           ...                 ...     ...  
2693                2             0                 5.0       0  
2694                2             1                 3.0       0  
2695                1             1                 NaN       0  
2696                0             1                 2.0       1  
2697                2             0                 4.0       0  

[2698 rows x 9 columns]

In [10]:
df_train_sub.mean().round(2)

age                      49.07
income                53628.35
account_duration         29.80
last_login_days         182.43
num_transactions         10.06
support_tickets           1.54
premium_user              0.49
satisfaction_score        2.99
target                    0.30
dtype: float64

In [12]:
df_train_sub = df_train_sub.fillna(df_train_sub.mean())
df_train_sub

age     income  account_duration  last_login_days  num_transactions  \
0      56   41315.55                 4        55.000000                11   
1      69   50955.33                30       228.000000                 9   
2      46   57079.42                30       144.000000                 9   
3      32   52088.23                13        91.000000                 5   
4      60  340461.50                42        81.000000                 3   
...   ...        ...               ...              ...               ...   
2693   27   58571.13                59       329.000000                 8   
2694   20   61771.72                13       339.000000                 8   
2695   71   59322.83                52       182.428865                 9   
2696   31   45010.14                48       154.000000                10   
2697   33   66405.46                42       159.000000                 8   

      support_tickets  premium_user  satisfaction_score  target  
0                   2             0            3.000000       1  
1                   1             0            2.992188       0  
2                   0             0            3.000000       0  
3                   3             0            2.000000       0  
4                   2             1            2.000000       0  
...               ...           ...                 ...     ...  
2693                2             0            5.000000       0  
2694                2             1            3.000000       0  
2695                1             1            2.992188       0  
2696                0             1            2.000000       1  
2697                2             0            4.000000       0  

[2698 rows x 9 columns]

In [13]:

X_train, y_train = df_train_sub.to_numpy()[:, :-1], df_train_sub.to_numpy()[:, -1]
y_train



array([1., 0., 0., ..., 0., 1., 0.], shape=(2698,))

In [14]:
from sklearn.linear_model import LogisticRegression

# Fix: instantiate LogisticRegression first, then call fit()
lr = LogisticRegression().fit(X_train, y_train)
lr

C:\Users\emili\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [15]:
lr.coef_

array([[-3.02111970e-03, -1.11284957e-06, -4.72401432e-03,
        -4.41238633e-04, -3.31359698e-02, -2.63867337e-03,
        -1.90028475e-03, -1.55042869e-02]])

In [16]:
lr.intercept_

array([-0.00383045])

In [ ]:
df_train_sub['target'] = lr.predict(X_train)
df_train_sub

age     income  account_duration  last_login_days  num_transactions  \
0      56   41315.55                 4        55.000000                11   
1      69   50955.33                30       228.000000                 9   
2      46   57079.42                30       144.000000                 9   
3      32   52088.23                13        91.000000                 5   
4      60  340461.50                42        81.000000                 3   
...   ...        ...               ...              ...               ...   
2693   27   58571.13                59       329.000000                 8   
2694   20   61771.72                13       339.000000                 8   
2695   71   59322.83                52       182.428865                 9   
2696   31   45010.14                48       154.000000                10   
2697   33   66405.46                42       159.000000                 8   

      support_tickets  premium_user  satisfaction_score  target  
0                   2             0            3.000000     0.0  
1                   1             0            2.992188     0.0  
2                   0             0            3.000000     0.0  
3                   3             0            2.000000     0.0  
4                   2             1            2.000000     0.0  
...               ...           ...                 ...     ...  
2693                2             0            5.000000     0.0  
2694                2             1            3.000000     0.0  
2695                1             1            2.992188     0.0  
2696                0             1            2.000000     0.0  
2697                2             0            4.000000     0.0  

[2698 rows x 9 columns]

In [ ]:
from sklearn.metrics import mean_absolute_error

mean_absolute_error(df_train_sub['target'], df_)

In [21]:
df_test_sub = df_test_sub.fillna(df_test_sub.mean())


df_test.columns

Index(['customer_id', 'age', 'income', 'signup_channel', 'country',
       'account_duration', 'last_login_days', 'num_transactions',
       'support_tickets', 'premium_user', 'satisfaction_score'],
      dtype='object')

In [23]:
df_test_final = df_test.drop(columns=['age', 'income', 'signup_channel', 'country',
       'account_duration', 'last_login_days', 'num_transactions',
       'support_tickets', 'premium_user', 'satisfaction_score'])
df_test_final

customer_id
0    CUST102698
1    CUST102699
2    CUST102700
3    CUST102701
4    CUST102702
..          ...
297  CUST102995
298  CUST102996
299  CUST102997
300  CUST102998
301  CUST102999

[302 rows x 1 columns]

In [30]:
X_test = df_test_sub.to_numpy()
X_test

array([[2.700000e+01, 4.813359e+04, 2.700000e+01, ..., 1.000000e+00,
        1.000000e+00, 5.000000e+00],
       [4.600000e+01, 4.146459e+04, 5.300000e+01, ..., 0.000000e+00,
        0.000000e+00, 1.000000e+00],
       [2.700000e+01, 4.168493e+04, 2.000000e+00, ..., 2.000000e+00,
        0.000000e+00, 1.000000e+00],
       ...,
       [7.100000e+01, 5.224034e+04, 4.600000e+01, ..., 0.000000e+00,
        1.000000e+00, 2.000000e+00],
       [2.400000e+01, 4.692157e+04, 3.000000e+00, ..., 0.000000e+00,
        0.000000e+00, 3.000000e+00],
       [7.100000e+01, 3.240265e+04, 2.000000e+00, ..., 2.000000e+00,
        0.000000e+00, 4.000000e+00]], shape=(302, 8))

In [32]:
df_test['target'] = lr.predict(X_test)
df_test

customer_id  age    income signup_channel  country  account_duration  \
0    CUST102698   27  48133.59           APP        US                27   
1    CUST102699   46  41464.59       Referral   Canada                53   
2    CUST102700   27  41684.93            app    India                 2   
3    CUST102701   29  79099.83            web       US                34   
4    CUST102702   47  38870.25           APP        US                31   
..          ...  ...       ...            ...      ...               ...   
297  CUST102995   37  26426.33           APP     India                 1   
298  CUST102996   21  38093.20            web   Canada                19   
299  CUST102997   71  52240.34       Referral  Germany                46   
300  CUST102998   24  46921.57            app  Germany                 3   
301  CUST102999   71  32402.65       referral       US                 2   

     last_login_days  num_transactions  support_tickets premium_user  \
0                NaN                 7                1            Y   
1                NaN                10                0            N   
2              167.0                16                2           No   
3              144.0                13                3            Y   
4              185.0                14                0         YES    
..               ...               ...              ...          ...   
297              NaN                 9                3          NO    
298            277.0                15                1            Y   
299             55.0                 9                0         YES    
300            273.0                14                0           No   
301            175.0                17                2          NO    

     satisfaction_score  target  
0                   5.0     0.0  
1                   1.0     0.0  
2                   1.0     0.0  
3                   3.0     0.0  
4                   5.0     0.0  
..                  ...     ...  
297                 1.0     0.0  
298                 1.0     0.0  
299                 2.0     0.0  
300                 3.0     0.0  
301                 4.0     0.0  

[302 rows x 12 columns]

In [33]:
df_test = df_test.drop(columns=['age', 'income', 'signup_channel', 'country',
       'account_duration', 'last_login_days', 'num_transactions',
       'support_tickets', 'premium_user', 'satisfaction_score'])
df_test

customer_id  target
0    CUST102698     0.0
1    CUST102699     0.0
2    CUST102700     0.0
3    CUST102701     0.0
4    CUST102702     0.0
..          ...     ...
297  CUST102995     0.0
298  CUST102996     0.0
299  CUST102997     0.0
300  CUST102998     0.0
301  CUST102999     0.0

[302 rows x 2 columns]

In [34]:
# Example: get unique values from the 'age' column in df_test_sub
df_test['target'].unique()


array([0.])